###
POST http://localhost:8010/receitas
Content-Type: application/json

{
  "name": "Torrada de presunto e queijo",
  "ingredients": [
    {
      "name": "pão"
    },{
      "name": "presunto"
    },{
      "name": "queijo"
    }
  ]
}

> {%
  client.test("Request executada com sucesso", function() {
    client.assert(response.status === 200, "Status de resposta não é 200");
  });
%}

###
GET http://localhost:8010/receitas

> {%
  client.test("Request executada com sucesso", function() {
    client.assert(response.status === 200, "Status de resposta não é 200");
    client.assert(response.body === "{\"torrada-de-presunto-e-queijo\":{\"name\":\"Torrada de presunto e queijo\",\"ingredients\":[{\"name\":\"pão\"},{\"name\":\"presunto\"},{\"name\":\"queijo\"}]}}", "Body match expected response")
  });
%}

###
GET http://localhost:8010/receitas/torrada-de-presunto-e-queijo

> {%
  client.test("Request executada com sucesso", function() {
    client.assert(response.status === 200, "Status de resposta não é 200");
    client.assert(response.body === "{\"name\":\"Torrada de presunto e queijo\",\"ingredients\":[{\"name\":\"pão\"},{\"name\":\"presunto\"},{\"name\":\"queijo\"}]}", "Body match expected response")
  });
%}

###
PUT  http://localhost:8010/receitas/torrada-de-presunto-e-queijo
Content-Type: application/json

{
  "name": "Torrada de presunto e queijo",
  "ingredients": [
    {
      "name": "pão"
    },{
      "name": "presunto"
    },{
      "name": "queijo"
    },{
      "name": "manteiga"
    }
  ]
}

> {%
  client.test("Request executada com sucesso", function() {
    client.assert(response.status === 200, "Status de resposta não é 200");
  });
%}

###
GET http://localhost:8010/receitas/torrada-de-presunto-e-queijo

> {%
  client.test("Request executada com sucesso", function() {
    client.assert(response.status === 200, "Status de resposta não é 200");
    client.assert(response.body === "{\"name\":\"Torrada de presunto e queijo\",\"ingredients\":[{\"name\":\"pão\"},{\"name\":\"presunto\"},{\"name\":\"queijo\"},{\"name\":\"manteiga\"}]}", "Body match expected response")

  });
%}

###
DELETE http://localhost:8010/receitas/torrada-de-presunto-e-queijo

> {%
  client.test("Request executada com sucesso", function() {
    client.assert(response.status === 200, "Status de resposta não é 200");
  });
%}

###
GET http://localhost:8010/receitas/torrada-de-presunto-e-queijo

> {%
  client.test("Request executada com sucesso", function() {
    client.assert(response.status === 404, "Response status is not 404");
  });
%}